proxies:
  - name: IKD
    server: 104.26.6.171
    port: 443
    type: trojan
    password: dfd55a47-6df6-4816-b2b0-b1a5c8639261
    skip-cert-verify: true
    sni: id-ikd.webkuy.my.id
    network: ws
    ws-opts:
      path: /trojan
      headers:
        Host: id-ikd.webkuy.my.id
    udp: true
  - name: Linode
    server: 104.26.6.171
    port: 443
    type: trojan
    password: 77ca39b0-1ef9-45bc-9937-491217566d8c
    skip-cert-verify: true
    sni: sg-linode4.estebuh.my.id
    network: ws
    ws-opts:
      path: /trojan
      headers:
        Host: sg-linode4.estebuh.my.id
    udp: true
  - name: GRATIS1
    server: 104.26.6.171
    port: 443
    type: trojan
    password: jagoanssh-28dessdssds
    skip-cert-verify: true
    sni: sgcgo.ipservers.xyz
    network: ws
    ws-opts:
      path: /trojan
      headers:
        Host: sgcgo.ipservers.xyz
    udp: true
  - name: GRATIS2
    server: 104.26.6.171
    type: vmess
    port: 443
    uuid: ddc2ddd3-192a-42e9-ae1e-96e98ac89344
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: sgm2ray.serverip.my.id
    network: ws
    ws-opts:
      path: /serverssh.net
      headers:
        Host: sgm2ray.serverip.my.id
    udp: true
  - name: GRATISSS
    server: 104.26.6.171
    type: vmess
    port: 443
    uuid: d6543624-68ad-437c-8573-25c4c52e6c70
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: idmws.mainssh.xyz
    network: ws
    ws-opts:
      path: /vmess
      headers:
        Host: idmws.mainssh.xyz
    udp: true
proxy-groups:
- name: ILMUPEDIA
  type: fallback
  disable-udp: false
  proxies:
  - IKD
  - Linode
  - GRATIS1
  - GRATIS2
  - GRATISSS
  url: http://www.gstatic.com/generate_204
  interval: '300'
rules:
- MATCH,ILMUPEDIA
