port: 7890
socks-port: 7891
redir-port: 7892
tproxy-port: 7895
mixed-port: 7893
allow-lan: true
mode: rule
log-level: silent
ipv6: false
external-controller: 0.0.0.0:9090
external-ui: folder
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:7874
  fallback-filter:
    geoip: true
    geoip-code: ID
    ipcidr:
    - 0.0.0.0/8
    - 10.0.0.0/8
    - 100.64.0.0/10
    - 127.0.0.0/8
    - 169.254.0.0/16
    - 172.24.0.0/16
    - 172.16.0.0/12
    - 192.0.0.0/24
    - 192.0.2.0/24
    - 192.88.99.0/24
    - 192.168.0.0/16
    - 198.18.0.0/15
    - 198.51.100.0/24
    - 203.0.113.0/24
    - 224.0.0.0/4
    - 240.0.0.0/4
    - 255.255.255.255/32
    domain:
    - "+.google.com"
    - "+.netflix.com"
    - "+.facebook.com"
    - "+.youtube.com"
    - "+.githubusercontent.com"
    - "+.googlevideo.com"
    - "+.msftconnecttest.com"
    - "+.msftncsi.com"
    - msftconnecttest.com
    - msftncsi.com
    fake-ip-filter:
    - "+.pool.ntp.org"
    - ntp7.*.com
    - ntp6.*.com
    - ntp5.*.com
    - ntp4.*.com
    - ntp3.*.com
    - ntp2.*.com
    - ntp1.*.com
    - ntp.*.com
    - time7.*.com
    - time6.*.com
    - time5.*.com
    - time4.*.com
    - time3.*.com
    - time2.*.com
    - time1.*.com
    - time.*.apple.com
    - time.*.edu.cn
    - time.*.gov
    - time.*.com
    - "*.home.arpa"
    - "*.local"
    - "*.test"
    - "*.localhost"
    - "*.invalid"
    - "*.example"
    - "*.localdomain"
    - time1.cloud.tencent.com
    - "*.ntp.org"
    - "*.time.edu"
    - "*.lan"
    - "*.ntp.org.cn"
    - "*.time.edu.cn"
    - "+.*"
  fake-ip-range: 198.18.0.1/16
  nameserver:
  - 1.1.1.1
  - 1.0.0.1
  - 8.8.8.8
  - 8.8.4.4
  - https://dns.cloudflare.com/dns-query
  - https://dns.google/dns-query
  - tls://1dot1dot1dot1.cloudflare-dns.com
  - tls://dns.google
  default-nameserver:
  - 1.1.1.1
  - 1.0.0.1
  - 8.8.8.8
  - 8.8.4.4
  fake-ip-filter:
  - "*.lan"
  - "*.localdomain"
  - "*.example"
  - "*.invalid"
  - "*.localhost"
  - "*.test"
  - "*.local"
  - "*.home.arpa"
  - time.*.com
  - time.*.gov
  - time.*.edu.cn
  - time.*.apple.com
  - time-ios.apple.com
  - time1.*.com
  - time2.*.com
  - time3.*.com
  - time4.*.com
  - time5.*.com
  - time6.*.com
  - time7.*.com
  - ntp.*.com
  - ntp1.*.com
  - ntp2.*.com
  - ntp3.*.com
  - ntp4.*.com
  - ntp5.*.com
  - ntp6.*.com
  - ntp7.*.com
  - "*.time.edu.cn"
  - "*.ntp.org.cn"
  - "+.pool.ntp.org"
  - time1.cloud.tencent.com
  - "+.msftconnecttest.com"
  - "+.msftncsi.com"
  - stun.*.*
  - stun.*.*.*
  - "+.stun.*.*"
  - "+.stun.*.*.*"
  - "+.stun.*.*.*.*"
  - "+.stun.*.*.*.*.*"
  - "*.linksys.com"
  - "*.linksyssmartwifi.com"
  - "*.router.asus.com"
  - mesu.apple.com
  - swscan.apple.com
  - swquery.apple.com
  - swdownload.apple.com
  - swcdn.apple.com
  - swdist.apple.com
  - lens.l.google.com
  - "+.google.com"
  - Mijia Cloud
  - "+.cmbchina.com"
  - "+.cmbimg.com"
  - music.163.com
  - "*.music.163.com"
  - "*.126.net"
  - musicapi.taihe.com
  - music.taihe.com
  - songsearch.kugou.com
  - trackercdn.kugou.com
  - "*.kuwo.cn"
  - api-jooxtt.sanook.com
  - api.joox.com
  - joox.com
  - y.qq.com
  - "*.y.qq.com"
  - streamoc.music.tc.qq.com
  - mobileoc.music.tc.qq.com
  - isure.stream.qqmusic.qq.com
  - dl.stream.qqmusic.qq.com
  - aqqmusic.tc.qq.com
  - amobile.music.tc.qq.com
  - "*.xiami.com"
  - "*.music.migu.cn"
  - music.migu.cn
  - msftconnecttest.com
  - msftncsi.com
  - localhost.ptlogin2.qq.com
  - localhost.sec.qq.com
  - "+.srv.nintendo.net"
  - "*.n.n.srv.nintendo.net"
  - "+.stun.playstation.net"
  - xbox.*.*.microsoft.com
  - "*.*.xboxlive.com"
  - xbox.*.microsoft.com
  - xnotify.xboxlive.com
  - "+.battlenet.com.cn"
  - "+.wotgame.cn"
  - "+.wggames.cn"
  - "+.wowsgame.cn"
  - "+.wargaming.net"
  - proxy.golang.org
  - heartbeat.belkin.com
  - stun.l.google.com
  - "+.nflxvideo.net"
  - "*.square-enix.com"
  - "*.finalfantasyxiv.com"
  - "*.ffxiv.com"
  - "*.ff14.sdo.com"
  - ff.dorado.sdo.com
  - "*.mcdn.bilivideo.cn"
  - "+.media.dssott.com"
  - "+.dns.google"
proxies:
  - name: LINODE
    server: 104.26.6.171
    type: vmess
    port: 443
    uuid: 8784fa3d-3e47-4980-8c1a-934d3fce8ee1
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: id-akamai.estebuh.my.id
    network: ws
    ws-opts:
      path: /vmess
      headers:
        Host: id-akamai.estebuh.my.id
    udp: true
  - name: SGDO
    server: 104.26.6.171
    port: 443
    type: trojan
    password: 11e7e663-d6c5-4d4b-99ef-9912330f0d07
    skip-cert-verify: true
    sni: sgp-rmatvpn.my.id
    network: ws
    ws-opts:
      path: /trojan
      headers:
        Host: sgp-rmatvpn.my.id
    udp: true
proxy-groups:
- name: ILMUPEDIA
  type: select
  disable-udp: false
  proxies:
  - LINODE
  - SGDO
  url: http://www.gstatic.com/generate_204
  interval: '300'
rules:
- MATCH,ILMUPEDIA
